package pojoClass;
// Generated Sep 3, 2018 7:40:07 AM by Hibernate Tools 4.3.1



/**
 * Login generated by hbm2java
 */
public class Login  implements java.io.Serializable {


    private LoginId id;

    public Login() {
    }

    public Login(LoginId id) {
       this.id = id;
    }
   
    public LoginId getId() {
        return this.id;
    }
    
    public void setId(LoginId id) {
        this.id = id;
    }

}


