package pojoClass;
// Generated Sep 3, 2018 7:40:07 AM by Hibernate Tools 4.3.1



/**
 * Login generated by hbm2java
 */
public class Login  implements java.io.Serializable {

    private Integer id;
    private String User_Name;
    private String User_Password;

    public Login() {
    }

    public Login(String User_Name, String User_Password) {
        this.User_Name = User_Name;
        this.User_Password = User_Password;
    }

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getUser_Name() {
        return User_Name;
    }

    public void setUser_Name(String User_Name) {
        this.User_Name = User_Name;
    }

    public String getUser_Password() {
        return User_Password;
    }

    public void setUser_Password(String User_Password) {
        this.User_Password = User_Password;
    }
    
}


