package pojoClass;
// Generated Sep 3, 2018 7:40:07 AM by Hibernate Tools 4.3.1

import java.sql.Blob;

/**
 * VipInfo generated by hbm2java
 */
public class VipInfo  implements java.io.Serializable {


    private Integer id;
    private String fullname;
    private String idNumber;
    private Blob image1;
    private Blob image2;
    private Blob image3;
    private Blob image4;
    private Blob image5;

    public VipInfo() {
    }
   
    public VipInfo(String fullname, String idNumber, Blob image1, Blob image2, Blob image3, Blob image4, Blob image5) {
       this.fullname = fullname;
       this.idNumber = idNumber;
       this.image1 = image1;
       this.image2 = image2;
       this.image3 = image3;
       this.image4 = image4;
       this.image5 = image5;
    }
    
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getFullname() {
        return this.fullname;
    }
    
    public void setFullname(String fullname) {
        this.fullname = fullname;
    }
    public String getIdNumber() {
        return this.idNumber;
    }
    
    public void setIdNumber(String idNumber) {
        this.idNumber = idNumber;
    }

    public Blob getImage1() {
        return image1;
    }

    public void setImage1(Blob image1) {
        this.image1 = image1;
    }

    public Blob getImage2() {
        return image2;
    }

    public void setImage2(Blob image2) {
        this.image2 = image2;
    }

    public Blob getImage3() {
        return image3;
    }

    public void setImage3(Blob image3) {
        this.image3 = image3;
    }

    public Blob getImage4() {
        return image4;
    }

    public void setImage4(Blob image4) {
        this.image4 = image4;
    }

    public Blob getImage5() {
        return image5;
    }

    public void setImage5(Blob image5) {
        this.image5 = image5;
    }

}


